server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的Rabbit的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置Rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input:
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型， 本次为JSON， 文本则设置 "text/plain"
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: atguiguA

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔
    lease-expiration-duration-in-seconds: 5 # 超过5s时
    instance-id: receive-8802.com # 在消息列表时显示的主机名称
    prefer-ip-address: true # 访问的路径变为ip地址
